server:
  port: 8080

spring:
  application:
    name: sims

  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-max
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.92.73.197:3306/sism?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=utf-8
    username: simsuser
    password: simssql



  data:
    redis:
      host: localhost
      database: 2
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /sims
    listener:
      simple:
        prefetch: 1

sims:
    jwt:
        secret-key: lihuabaiaq123456789987654321123456789
        ttl-millis: 86400000000
        token-name: Authorization

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.sims.controller
knife4j:
  enable: true
  setting:
    language: zh_cn

mybatis-plus:
  type-aliases-package: com.sims.pojo.entity

logging:
  level:
    com.sims: info
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    name: "logs/sims"